config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :novels
  root :to => "novels#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/novel.rb
class Novel < ApplicationRecord
  validates_presence_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/novels_controller.rb
class NovelsController < ApplicationController
  before_action :id_find, :only => [:show, :edit, :update, :destroy]
  def index
    @novels = Novel.page(params[:page]).per(5)
  end
  def new
    @novel = Novel.new
  end
  def create
    @novel = Novel.new(param_novel)
    if @novel.save
      flash[:notice] = "新增成功"
      redirect_to novels_path
    else
      flash[:alert] = "新增失敗"
      render "new"
    end
  end
  def show
    @page_title = @novel.name
  end
  def edit
  end
  def update
    if @novel.update(param_novel)
      flash[:notice] = "修改成功"
      redirect_to novels_path
    else
      flash[:alert] = "修改失敗"
      render "edit"
    end
  end
  def destroy
    @novel.destroy
    flash[:notice] = "刪除成功"
    redirect_to novels_path
  end

  private
  def id_find
    @novel = Novel.find(params[:id])
  end
  def param_novel
    params.require(:novel).permit(:name, :genre, :description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/novels_helper.rb
module NovelsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Book</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p style="color: green"><%= flash[:notice] %></p>
    <p style="color: red"><%= flash[:alert] %></p>
    <%= yield %>
  </body>
</html>

app/views/novels/_form.html.erb
<%=f.label :name, "小說名稱"%>
  <%=f.text_field :name %>
  <%=f.label :genre, "小說類型"%>
  <%=f.text_field :genre %>
  <%=f.label :description, "小說簡介"%>
  <%=f.text_area :description %>

app/views/novels/edit.html.erb
<%=form_for @novel, :url => novel_path(@novel), :method => :patch do |f| %>
  <%=render :partial =>"form",:locals =>{:f=>f}%>
  <%=f.submit "修改內容"%>
<%end%>

<%=link_to "返回主頁", novels_path%>

app/views/novels/index.html.erb
<h2>小說清單</h2>
<ul>
  <%@novels.each do |n|%>
    <li>小說名稱：<%=n.name%>
        <%= link_to "內容", novel_path(n) %>
        <%= link_to "修改內容", edit_novel_path(n) %>
        <%=link_to "刪除", novel_path(n), :method =>:delete%>
    </li>
  <%end%>
</ul>

<%= paginate @novels %>
<%=link_to "新增小說", new_novel_path%>

app/views/novels/new.html.erb
<%=form_for @novel, :url => novels_path, :method => :post do |f| %>
  <%=render :partial =>"form",:locals =>{:f=>f}%>
  <%=f.submit "新增小說"%>
<%end%>

<%=link_to "返回主頁", novels_path%>

app/views/novels/show.html.erb
<p>小說名稱：<%=@novel.name%></p>
<p>小說類型：<%=@novel.genre%></p>
<p>小說內容：<%=@novel.description%></p>
<%=link_to "返回主頁", novels_path%>